# Generated by Django 4.1.5 on 2023-01-26 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="room",
            old_name="created_at",
            new_name="createdTime",
        ),
        migrations.RenameField(
            model_name="room",
            old_name="guest_can_pause",
            new_name="guestCanPause",
        ),
        migrations.RenameField(
            model_name="room",
            old_name="votes_to_skip",
            new_name="skipVotes",
        ),
    ]
