# Generated by Django 4.1.5 on 2023-01-28 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_room_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="song",
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
