# Generated by Django 4.1.5 on 2023-01-28 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_alter_room_song"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="song",
        ),
    ]
