# Generated by Django 4.1.5 on 2023-01-28 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_remove_room_song"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="song",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
