# Generated by Django 4.1.5 on 2023-01-27 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SpotifyToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(max_length=50, unique=True)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("refreshToken", models.CharField(max_length=150)),
                ("accessToken", models.CharField(max_length=150)),
                ("expiresIn", models.DateTimeField()),
                ("tokenType", models.CharField(max_length=50)),
            ],
        ),
    ]
