# Generated by Django 4.1.5 on 2023-01-28 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_room_song"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="song",
            field=models.CharField(default="", max_length=50, null=True),
        ),
    ]
