# Generated by Django 4.1.5 on 2023-01-28 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spotifyapi", "0002_votes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="votes",
            name="songId",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
