# Generated by Django 4.1.5 on 2023-01-28 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("spotifyapi", "0003_alter_votes_songid"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Votes",
        ),
    ]
